# Generated by Django 2.0.4 on 2018-04-10 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0007_auto_20180410_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='uname',
        ),
    ]
