# Generated by Django 2.0.4 on 2018-04-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0008_remove_blog_uname'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
