# Generated by Django 2.0.4 on 2018-04-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0009_blog_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='ans',
            field=models.CharField(default='', max_length=100),
        ),
    ]
