# Generated by Django 2.0.4 on 2018-04-12 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0011_blog_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_post',
            old_name='blogp',
            new_name='blogpost',
        ),
    ]
