# Generated by Django 2.0.4 on 2018-04-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0012_auto_20180412_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='blogpost',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='ans',
            field=models.CharField(max_length=100),
        ),
    ]
