# Generated by Django 2.0.4 on 2018-04-13 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0013_auto_20180412_0630'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog_Post',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
